export { Content,
Footer,
Image,
Table,
Notification,
Columns, Column,
Message, MessageBody, MessageHeader,
Panel, PanelTabs, PanelBlock, PanelHeading,
Menu, MenuLabel, MenuList,
Section,
Box,
Container,
Title, Subtitle,
Element, 
Button,
Close,
Tag,
Icon,
Navbar, NavbarBurger, NavbarMenu,
Media, MediaLeft, MediaRight, MediaContent,
Level, LevelLeft, LevelRight, LevelItem,
Breadcrumb, BreadcrumbItem,
Modal, ModalClose, ModalBackground, ModalContent,
ModalCard, ModalCardHead, ModalCardBody, ModalCardFoot,
Hero, HeroHead, HeroBody, HeroFoot,
Select, Textarea, Label, Radio, Checkbox, Input, Field, Control, Help,
Card, CardHeader, CardHeaderTitle, CardHeaderIcon, CardContent, CardImage, CardFooter
} from 'components/index'

export const Delete = Close
